magazine/config/routes.rb
Rails.application.routes.draw do
  resources :articles

  get 'home/index'
  get 'home/foo'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "home#index"
  # root "articles#new" would make the default home page of the site to new articles form.
end

magazine/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

magazine/app/models/article.rb
class Article < ApplicationRecord
    validates :title, presence: true, length: { minimum: 5 }
end

magazine/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

magazine/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: [:show, :edit, :update, :destroy]
    
    def index
        @articles = Article.all
    end

    def new
        @article = Article.new
    end
    
    def create
        # render json: params[:article]
        
        # Create new instance of the Article model,
        # populate with data from the params hash
        @article = Article.new(article_params)
        # Save the new article to the db
        if @article.save
            redirect_to @article
        else
            render 'new'
        end
        # Redirect to the page for viewing a single article
    end
    
    def show
        # @article = Article.find(params[:id])
    end
    
    def edit
        # @article = Article.find(params[:id])
    end

    def update
        # @article = Article.find(params[:id])
        if @article.update(article_params)
            redirect_to @article
        else
            render 'edit'
        end
    end

    def destroy
        # @article = Article.find(params[:id])
        @article.destroy
        redirect_to articles_path
    end

    private
    
    def article_params
        params.require(:article).permit(:title, :content)
    end

    def set_article
        @article = Article.find(params[:id])
    end
end

magazine/app/controllers/foo_controller.rb
class FooController < ApplicationController
  def bar
  end
  def hello
  end
end

magazine/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

magazine/app/helpers/application_helper.rb
module ApplicationHelper
end

magazine/app/helpers/articles_helper.rb
module ArticlesHelper
end

magazine/app/helpers/home_helper.rb
module HomeHelper
end

magazine/app/views/articles/_form.html.erb
<style>
    li {
        color: red;
        }
</style>

<% if article.errors.any? %>
    <ul>
        <% for msg in article.errors.full_messages %>
            <li><%= msg %></li>
        <% end %>
    </ul>
<% end %>

<%= form_for(article) do |f| %>
    <p>
        <%= f.label :title %><br>
        <%= f.text_field :title %>
    </p>
    <p>
        <%= f.label :content %><br>
        <%= f.text_area :content %>
    </p>
    <p>
        <%= f.submit %>
    </p>
<% end %>

<%= link_to 'Back to Articles', articles_path %>

magazine/app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render 'form', article: @article %>

magazine/app/views/articles/index.html.erb
<style>
    body {
        background: blue;
        color: white;
        /* display: flex;
        flex-direction: row-reverse;
        justify-content: center;
        align-items: center; */
    }

    a {
        color: yellow;
    }
</style>

<h1>All Articles</h1>

<%= link_to 'Home', home_index_path %> <%= link_to 'New article', new_article_path %>
<br>
<br>
<table>
    <tr>
        <th>Title</th>
        <th>Content</th>
    </tr>
    <% @articles.each do |article| %>
        <tr>
            <td><%= link_to article.title, article %></td>
            <td><%= article.content %></td>
            <td><%= link_to 'Edit', edit_article_path(article) %></td>
            <td><%= link_to 'Delete', article_path(article), method: :delete, data: { confirm: "Press 'OK' if you're a dickhead?" } %></td>
        </tr>
    <% end %>
</table>

magazine/app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

magazine/app/views/articles/show.html.erb
<p>
    <strong>Title:</strong>
    <%= @article.title %>
</p>

<p>
    <strong>Content:</strong>
    <%= @article.content %>
</p>

<%= link_to 'Back to Articles', articles_path %>

<%= link_to 'Edit Article', edit_article_path %>

<%= link_to "Delete Article", article_path, method: :delete, data: { confirm: 'Are you a dickhead?' } %>

magazine/app/views/home/index.html.erb
<h1>Home#index</h1>

<p>Find me in app/views/home/index.html.erb</p>

<%= link_to 'My Magazine Articles', { controller: 'articles' } %>